### ISSUE TITLE
[DEV] Adjust dashboards for #672

### ISSUE THREAD

**Issue by ericvaandering** [dmwm/CMSRucio#673]
**Task description**
Dashboards should be updated to use metrics beginning with `rucio_probes_`

- [ ] https://monit-grafana.cern.ch/d/Qqtk3l-Zz/rucio-probes?viewPanel=67
- [ ] https://monit-grafana.cern.ch/d/9g_cqlNWk/rucio-prometheus-checking?viewPanel=76 
- [ ] https://monit-grafana.cern.ch/d/Qqtk3l-Zz/rucio-probes?viewPanel=83
- [ ] https://monit-grafana.cern.ch/d/Qqtk3l-Zz/rucio-probes?viewPanel=82
- [ ] https://monit-grafana.cern.ch/d/Qqtk3l-Zz/rucio-probes?viewPanel=76

**Related issues**

#672 

**Technical Implementation**
Describe the technical implementation needed, and what are the expected problems/questions 

**Action items**
Sub-Items to be tracked
- []

**Comment by Panos512** [comment]
For this we would first need to merge https://github.com/rucio/probes/pull/134 which reworks how we push storage usage numbers in Prometheus. @ericvaandering can you please have at your convenience 

Then changing the dashboards above will be trivial but I believe we should actually rethink those "Rucio Probes" dashboards.

@haozturk has already created a great dashboard using the data coming from the rule-related probes
I can create a new dashboard for Space Usage once we merge the PR above and then we can retire all the old dashboards.

What do you guys think?

**Comment by haozturk** [comment]
Panels can be in the same dashboard as long as they share the same filters. If not, we should have a separate dashboard. On the first glance, it looks like it's more appropriate to have a separate dashboard for this issue as you suggest Panos.

**Comment by ericvaandering** [comment]
OK, I merged. Go ahead. I think whatever dashboards you (or others) will find useful are what you should do. 

I do think that a dashboard should have about one screen of information. We have some "dashboards" where there are 5 pages of info. For sure ~no one ever scrolls to the bottom. :-)

**Comment by Panos512** [comment]
I'm closing this one since the new probes for RSE usage have been used in the production  "Rucio used space in disk and tape" dashboard https://monit-grafana.cern.ch/d/O7M3h-UMk/rucio-used-space-in-disk-and-tape?orgId=11
