### ISSUE TITLE
[DEV] Remove probes and dashboards for several probes

### ISSUE THREAD

**Issue by ericvaandering** [dmwm/CMSRucio#674]
**Task description**
The probes and dashboards should be removed for 

- check_expected_total_number_of_files_per_rse_expression
- check_rules_with_0_completion_volume
- summary_probe

Dashboards:

- https://monit-grafana.cern.ch/d/Qqtk3l-Zz/rucio-probes?viewPanel=44
- https://monit-grafana.cern.ch/d/Qqtk3l-Zz/rucio-probes?viewPanel=32

Consists of 

- [x] Turn off running on probe in flux
- [ ] Move code to attic in probes
- [x] Remove or make attic of dashboard
- [x] Remove any related patches from Dockerfile

**Related issues**
Link to bug or feature request issues

**Technical Implementation**
Describe the technical implementation needed, and what are the expected problems/questions 

**Action items**
Sub-Items to be tracked
- []
