### ISSUE TITLE
Meta: Suspicious replica recovery roadmap

### ISSUE THREAD

**Issue by haozturk** [dmwm/CMSRucio#805]
### Feature Description

This is a meta issue to track down the steps to achieve suspicious replica recovery in CMS

- [x] [Short-term solution: Set up a cron job to check and recover suspicious replicas that CRAB reports](https://its.cern.ch/jira/browse/CMSTRANSF-883 )
- [x] Configure kronos with `bad_file_patterns` to mark replicas suspicious
- [x] [Fix the rucio problems that's preventing conveyor-finisher to mark replicas suspicious ](https://github.com/dmwm/CMSRucio/issues/692)
- [x] [Deploy the suspicious_replica_recoveror daemon](https://github.com/dmwm/CMSRucio/issues/806)
- [x] Deploy the minos_temporary_expiration daemon
- [ ] [Implement monitoring ](https://github.com/dmwm/CMSRucio/issues/862)
- [ ] [Update WMArchive so that it provides PFNs to /topic/cms.jobmon.wmarchive](https://github.com/dmwm/WMCore/issues/10879)
- [ ] [Update rucio-tracers so that it propagates PFNs and error messages to Rucio](https://github.com/dmwm/CMSRucio/issues/691)

### Use Case

https://indico.cern.ch/event/1356295/

### Possible Solution

NA

### Related Issues

This was the initial issue where this was discussed: https://github.com/dmwm/CMSRucio/issues/403
Rucio issues and PRs:
- https://github.com/rucio/rucio/issues/6396
- https://github.com/rucio/rucio/pull/6444
